exclude_paths:
    - docs/**/*
    - tests/**/*
    - gii/**/*
    
ratings:
    paths:
        - controllers/**
        - models/**
        - views/**
        - widgets/**
        - Module
        
engines:
    phpmd:
        enabled: true
    phpcodesniffer:
        enabled: true