language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: 5.4
        
sudo: true

branches:
    except:
        - gh-pages
        
services:
    - mysql
    - redis-server
    - mongodb

env:
    - DB=mysql
    
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
    - export PATH="$HOME/.composer/vendor/bin/:$PATH"
    - travis_retry composer install --prefer-dist --no-interaction
    
before_script:
    - php -r "echo INTL_ICU_VERSION . \"\n\";"
    - php -v
    - mysql --version
    - mysql -uroot < tests/data/yii2-models.sql
    - |
        if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
            travis_retry wget https://phar.phpunit.de/phpunit.phar
            chmod +x phpunit.phar
        fi
        
script: 
    - |
        if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
            php phpunit.phar --verbose --debug
        else
            phpunit --verbose --debug
        fi
